# Generated by Django 6.0.3 on 2026-03-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='agent_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
