# Generated by Django 6.0.3 on 2026-03-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_agent_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_executive',
            field=models.BooleanField(default=False),
        ),
    ]
