# Generated by Django 6.0.3 on 2026-03-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_is_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='capture_interval_minutes',
            field=models.IntegerField(blank=True, help_text='Si se establece, sobreescribe el intervalo global para este empleado.', null=True, verbose_name='Intervalo de captura (minutos)'),
        ),
    ]
