# Generated by Django 6.0.3 on 2026-03-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_capture_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='agent_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
