# Generated by Django 6.0.3 on 2026-03-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_screenshots_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skylog_access',
            field=models.BooleanField(default=True, help_text='Deshabilitar bloquea el acceso al agente y al dashboard de este empleado.', verbose_name='Acceso a Skylog'),
        ),
    ]
