# Generated by Django 6.0.3 on 2026-03-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_skylog_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='agent_online',
            field=models.BooleanField(default=False),
        ),
    ]
