# Generated by Django 6.0.3 on 2026-04-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_is_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='solo_movil',
            field=models.BooleanField(default=False, help_text='Si está activo, el empleado no necesita el agente de escritorio. El dashboard estará completamente habilitado sin requerir que el agente esté instalado o activo.', verbose_name='Solo móvil'),
        ),
    ]
