# Generated by Django 6.0.3 on 2026-04-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_solo_movil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_mobile',
        ),
    ]
