# Generated by Django 6.0.3 on 2026-04-20 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_remove_is_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='haber_basico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Haber básico'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hora_entrada',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Hora de referencia para calcular atrasos. Default: 08:00', verbose_name='Hora de entrada'),
        ),
    ]
