# Generated by Django 6.0.3 on 2026-04-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_cargo_employee_haber_basico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
