# Generated by Django 6.0.3 on 2026-04-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_remove_department_rename_to_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ciudad',
            field=models.CharField(choices=[('NONE', 'Sin catering'), ('LPZ', 'La Paz'), ('CBA', 'Cochabamba'), ('SCZ', 'Santa Cruz')], default='NONE', help_text='Ciudad donde recibe catering en el certificado de pago. Si no aplica, dejar en "Sin catering".', max_length=4, verbose_name='Ciudad (catering)'),
        ),
    ]
