# Generated by Django 6.0.3 on 2026-04-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='item_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Orden del empleado en el Certificado de Pago (1, 2, 3…). Empleados sin número aparecen al final ordenados por nombre.', null=True, verbose_name='N° Ítem'),
        ),
    ]
