# Generated by Django 6.0.6 on 2026-06-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employee_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile_type',
            field=models.CharField(blank=True, choices=[('gps', 'Solo coordenadas'), ('report', 'Reporte diario')], help_text='Solo coordenadas: captura GPS al iniciar y finalizar. Reporte diario: debe completar reporte al finalizar.', max_length=10, null=True, verbose_name='Tipo móvil'),
        ),
    ]
