# Generated by Django 6.0.6 on 2026-06-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_mobile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile_device_id',
            field=models.CharField(blank=True, default='', help_text='Se asigna automáticamente al primer login. Borrar para permitir vincular un nuevo dispositivo.', max_length=64, verbose_name='ID de dispositivo móvil'),
        ),
    ]
