# Generated by Django 6.0.6 on 2026-06-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_full_name_uppercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_edit_tags',
            field=models.BooleanField(default=False, help_text='Habilita el acceso a la gestión de etiquetas (proyectos, sedes, entregables).', verbose_name='Puede editar etiquetas'),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_message_leads',
            field=models.BooleanField(default=False, help_text='Habilita un botón para enviar un mensaje a todos los Supervisores y/o Project Managers.', verbose_name='Puede enviar mensajes a Sup/PM'),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_view_stats',
            field=models.BooleanField(default=False, help_text='Habilita el acceso a las estadísticas de todos los empleados (las que ven los ejecutivos).', verbose_name='Puede ver estadísticas globales'),
        ),
    ]
