# Generated by Django 6.0.6 on 2026-06-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_employee_can_edit_tags_employee_can_message_leads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_view_report',
            field=models.BooleanField(default=False, help_text='Habilita el acceso al registro de asistencia (las que ven los ejecutivos).', verbose_name='Puede ver registro de asistencia'),
        ),
    ]
