# Generated by Django 6.0.6 on 2026-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_employee_can_view_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_manage_visits',
            field=models.BooleanField(default=False, help_text='Habilita el acceso al módulo de Visitas para dar de alta usuarios externos con acceso solo a estadísticas.', verbose_name='Puede gestionar visitas'),
        ),
    ]
