# Generated by Django 6.0.3 on 2026-03-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'En progreso'), ('completed', 'Completada'), ('incomplete', 'Incompleta')], default='in_progress', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_done', models.TextField()),
                ('activities_planned', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('workday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report', to='workdays.workday')),
            ],
            options={
                'verbose_name': 'Reporte diario',
                'verbose_name_plural': 'Reportes diarios',
            },
        ),
        migrations.AddIndex(
            model_name='workday',
            index=models.Index(fields=['employee', 'status'], name='workdays_wo_employe_1a964a_idx'),
        ),
    ]
