# Generated by Django 6.0.3 on 2026-03-29 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_interval_minutes', models.IntegerField(default=30, help_text='Intervalo por defecto para todos los empleados. Rango: 1–480 min.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(480)], verbose_name='Intervalo de captura (minutos)')),
            ],
            options={
                'verbose_name': 'Configuración de capturas',
                'verbose_name_plural': 'Configuración de capturas',
            },
        ),
    ]
