# Generated by Django 6.0.3 on 2026-03-31 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0002_capture_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactivityPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_periods', to='workdays.workday')),
            ],
            options={
                'verbose_name': 'Período de inactividad',
                'verbose_name_plural': 'Períodos de inactividad',
                'ordering': ['started_at'],
            },
        ),
    ]
