# Generated by Django 6.0.3 on 2026-04-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_agent_online'),
        ('workdays', '0003_inactivityperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_messages', to='employees.employee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Mensaje ejecutivo',
                'verbose_name_plural': 'Mensajes ejecutivos',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', 'acknowledged_at'], name='workdays_ex_recipie_31c215_idx')],
            },
        ),
    ]
