# Generated by Django 6.0.3 on 2026-04-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0007_mobile_location'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendarnote',
            new_name='workdays_ca_date_d31a8a_idx',
            old_name='workdays_ca_date_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeleave',
            new_name='workdays_em_employe_89fe23_idx',
            old_name='workdays_em_emp_dates_idx',
        ),
    ]
