# Generated by Django 6.0.6 on 2026-06-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0008_rename_workdays_ca_date_idx_workdays_ca_date_d31a8a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivemessage',
            name='day_closed',
            field=models.BooleanField(default=False),
        ),
    ]
