# Generated by Django 6.0.6 on 2026-06-10 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0009_executive_message_day_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('done', 'Realizada'), ('planned', 'Planificada')], max_length=10)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('riesgos', 'Análisis de riesgos'), ('reuniones', 'Reuniones y coordinación'), ('cronogramas', 'Cronogramas y planificación'), ('diseno', 'Diseño e ingeniería'), ('supervision', 'Supervisión de obra y campo'), ('informes', 'Informes y reportes'), ('seguimiento', 'Seguimiento y control'), ('gestion_doc', 'Gestión documental y administrativa'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('matched_keyword', models.CharField(blank=True, default='', max_length=60)),
                ('manual_override', models.BooleanField(default=False, help_text='Categoría asignada manualmente; el clasificador no la sobreescribe.')),
                ('classified_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_items', to='workdays.dailyreport')),
            ],
            options={
                'verbose_name': 'Ítem de actividad',
                'verbose_name_plural': 'Ítems de actividad',
                'ordering': ['report_id', 'kind', 'position'],
                'indexes': [models.Index(fields=['category'], name='workdays_ac_categor_35bca2_idx'), models.Index(fields=['kind', 'category'], name='workdays_ac_kind_aa4534_idx')],
                'constraints': [models.UniqueConstraint(fields=('report', 'kind', 'position'), name='uniq_item_per_report_kind_pos')],
            },
        ),
    ]
