# Generated by Django 6.0.6 on 2026-06-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0010_activityitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityitem',
            name='category',
            field=models.CharField(choices=[('riesgos', 'Análisis de riesgos'), ('reuniones', 'Reuniones y coordinación'), ('cronogramas', 'Cronogramas y planificación'), ('actas', 'Actas y documentos de proyecto'), ('pliegos', 'Pliegos y especificaciones técnicas'), ('diseno', 'Diseño e ingeniería'), ('supervision', 'Supervisión de obra y campo'), ('informes', 'Informes y reportes'), ('seguimiento', 'Seguimiento y control'), ('gestion_doc', 'Gestión documental y administrativa'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
