# Generated by Django 6.0.6 on 2026-06-11 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_full_name_uppercase'),
        ('workdays', '0011_alter_activityitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivemessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='employees.employee'),
        ),
    ]
