# Generated by Django 6.0.6 on 2026-06-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0012_alter_executivemessage_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('color', models.CharField(default='#64748b', help_text='Color (hex) para gráficos del dashboard.', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Si está activa se ofrece al clasificador LLM.')),
                ('is_protected', models.BooleanField(default=False, help_text='Categoría base: no se puede borrar ni cambiar su código.')),
            ],
            options={
                'verbose_name': 'Categoría de actividad',
                'verbose_name_plural': 'Categorías de actividad',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='activityitem',
            name='source',
            field=models.CharField(choices=[('keyword', 'Palabras clave'), ('llm', 'LLM')], default='keyword', max_length=10),
        ),
        migrations.AlterField(
            model_name='activityitem',
            name='category',
            field=models.CharField(default='otros', max_length=20),
        ),
    ]
