# Generated by Django 6.0.6 on 2026-06-11 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0014_seed_activitycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('project', 'Proyecto'), ('location', 'Ubicación'), ('deliverable', 'Entregable')], max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='workdays.activitytag')),
            ],
            options={
                'verbose_name': 'Etiqueta de actividad',
                'verbose_name_plural': 'Etiquetas de actividad',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='activityitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='workdays.activitytag'),
        ),
        migrations.AddIndex(
            model_name='activitytag',
            index=models.Index(fields=['kind'], name='workdays_ac_kind_7d80f5_idx'),
        ),
        migrations.AddIndex(
            model_name='activitytag',
            index=models.Index(fields=['canonical'], name='workdays_ac_canonic_eeb072_idx'),
        ),
        migrations.AddConstraint(
            model_name='activitytag',
            constraint=models.UniqueConstraint(fields=('kind', 'key'), name='uniq_tag_kind_key'),
        ),
    ]
