# Generated by Django 6.0.6 on 2026-06-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0015_activitytag_activityitem_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytag',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
    ]
