# Generated by Django 6.0.6 on 2026-06-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0016_activitytag_ignored'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytag',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
