# Generated by Django 6.0.6 on 2026-06-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0017_activitytag_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytag',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
