# Generated by Django 6.0.6 on 2026-06-12 22:19

from django.db import migrations, models


def dismiss_existing_acknowledged(apps, schema_editor):
    """Los mensajes ya confirmados antes de esta feature se descartan para que no
    reaparezcan en el dashboard ahora que los leídos persisten hasta borrarse."""
    ExecutiveMessage = apps.get_model('workdays', 'ExecutiveMessage')
    ExecutiveMessage.objects.filter(acknowledged_at__isnull=False).update(dismissed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0020_seed_revision_tecnica_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivemessage',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(dismiss_existing_acknowledged, migrations.RunPython.noop),
    ]
