# Generated by Django 6.0.6 on 2026-06-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0021_executivemessage_dismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='leave_type',
            field=models.CharField(choices=[('vacacion', 'Vacación'), ('licencia', 'Licencia'), ('permiso', 'Permiso'), ('otro', 'Otro')], max_length=20),
        ),
    ]
