# Generated by Django 6.0.3 on 2026-03-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('workdays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='employees.employee')),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='workdays.workday')),
            ],
            options={
                'verbose_name': 'Captura de pantalla',
                'verbose_name_plural': 'Capturas de pantalla',
                'ordering': ['-captured_at'],
            },
        ),
    ]
