from django.urls import path
from .views import (
    WorkdayStartView, WorkdayEndView, ActiveWorkdayView, LastReportView,
    EmployeeOverviewView, CaptureNowView, EmployeeScreenshotsToggleView,
    EmployeeSkylogToggleView, SendMessageView, PendingMessagesView,
    AcknowledgeMessageView, DismissMessageView, WorkdayMonthlyView, EmployeeMonthlyView,
    CalendarNotesView, CalendarNoteDetailView, EmployeeLeavesView, EmployeeLeaveDetailView,
    ReporteAPIView, ReporteExportView, CertificadoExportView, ResetMobileDeviceView,
    EmployeePendingMessagesView, EmployeeViewDataView, CloseStaleWorkdaysView, CloseDayMessagesView,
    DoneActivitiesView, ClassifyDoneView, TagsListView, TagMergeView, TagIgnoreView,
    TagUnmergeView, TagRenameView, TagEmployeesView, EstadisticasAPIView, MisEstadisticasView,
    MessageLeadsView, AdminPermissionsListView, AdminPermissionsUpdateView,
)

urlpatterns = [
    path('workday/start/', WorkdayStartView.as_view()),
    path('workday/end/', WorkdayEndView.as_view()),
    path('workday/active/', ActiveWorkdayView.as_view()),
    path('workday/last-report/', LastReportView.as_view()),
    path('employees/overview/', EmployeeOverviewView.as_view()),
    path('employees/<int:employee_id>/capture/', CaptureNowView.as_view()),
    path('employees/<int:employee_id>/screenshots/', EmployeeScreenshotsToggleView.as_view()),
    path('employees/<int:employee_id>/skylog/', EmployeeSkylogToggleView.as_view()),
    path('employees/<int:employee_id>/message/', SendMessageView.as_view()),
    path('messages/pending/', PendingMessagesView.as_view()),
    path('messages/leads/', MessageLeadsView.as_view()),
    path('messages/<int:message_id>/acknowledge/', AcknowledgeMessageView.as_view()),
    path('messages/<int:message_id>/dismiss/', DismissMessageView.as_view()),
    path('admin/permissions/', AdminPermissionsListView.as_view()),
    path('admin/permissions/<int:employee_id>/', AdminPermissionsUpdateView.as_view()),
    path('workday/monthly/', WorkdayMonthlyView.as_view()),
    path('employees/<int:employee_id>/monthly/', EmployeeMonthlyView.as_view()),
    path('calendar/notes/', CalendarNotesView.as_view()),
    path('calendar/notes/<int:note_id>/', CalendarNoteDetailView.as_view()),
    path('employees/<int:employee_id>/leaves/', EmployeeLeavesView.as_view()),
    path('employees/<int:employee_id>/leaves/<int:leave_id>/', EmployeeLeaveDetailView.as_view()),
    path('employees/<int:employee_id>/reset-device/', ResetMobileDeviceView.as_view()),
    path('employees/<int:employee_id>/messages/', EmployeePendingMessagesView.as_view()),
    path('employees/<int:employee_id>/view-data/', EmployeeViewDataView.as_view()),
    path('internal/close-stale-workdays/', CloseStaleWorkdaysView.as_view()),
    path('internal/close-day-messages/', CloseDayMessagesView.as_view()),
    path('internal/done-activities/', DoneActivitiesView.as_view()),
    path('internal/classify-done/', ClassifyDoneView.as_view()),
    path('reporte/', ReporteAPIView.as_view()),
    path('reporte/export/', ReporteExportView.as_view()),
    path('reporte/export-certificado/', CertificadoExportView.as_view(), name='reporte-export-certificado'),
    path('estadisticas/', EstadisticasAPIView.as_view()),
    path('mis-estadisticas/', MisEstadisticasView.as_view()),
    path('tags/', TagsListView.as_view()),
    path('tags/merge/', TagMergeView.as_view()),
    path('tags/unmerge/', TagUnmergeView.as_view()),
    path('tags/ignore/', TagIgnoreView.as_view()),
    path('tags/<int:tag_id>/rename/', TagRenameView.as_view()),
    path('tags/<int:tag_id>/employees/', TagEmployeesView.as_view()),
]
